export const Ingredients = {
    CheeseCrust: "/assets/ingredients/Cheese Crust.png",
    CreamyMozzarella: "/assets/ingredients/Creamy Mozzarella.png",
    CheddarParmesanCheeses: "/assets/ingredients/Cheddar and Parmesan Cheeses.png",
    SpicyJalapeñoPepper: "/assets/ingredients/Spicy Jalapeño Pepper.png",
    TenderChicken: "/assets/ingredients/Tender Chicken.png",
    Mushrooms: "/assets/ingredients/Mushrooms.png",
    Bacon: "/assets/ingredients/Bacon.png",
    Ham: "/assets/ingredients/Ham.png",
    SpicyPepperoni: "/assets/ingredients/Spicy Pepperoni.png",
    SpicyChorizo: "/assets/ingredients/Spicy Chorizo.png",
    Pickles: "/assets/ingredients/Pickles.png",
    FreshTomatoes: "/assets/ingredients/Fresh Tomatoes.png",
    RedOnion: "/assets/ingredients/Red Onion.png",
    JuicyPineapple: "/assets/ingredients/Juicy Pineapple.png",
    ItalianHerbs: "/assets/ingredients/Italian Herbs.png",
    SweetPepper: "/assets/ingredients/Sweet Pepper.png",
    FetaCheeseCubes: "/assets/ingredients/Feta Cheese Cubes.png",
    Meatballs: "/assets/ingredients/Meatballs.png",
}